# Generated by Django 6.0.8 on 2026-08-28 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CtlBccrTc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('tc_compra', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('tc_venta', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('fuente', models.TextField(blank=True, null=True)),
                ('sobre', models.TextField(blank=True, null=True)),
                ('corrida', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ctl_bccr_tc',
                'ordering': ['-fecha'],
            },
        ),
    ]
