# Generated by Django 6.0.8 on 2026-08-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicop', '0002_ctlbccrtc'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sicopadjudicacionesfirme',
            index=models.Index(fields=['NRO_SICOP'], name='sicop_adjud_NRO_SIC_091c4b_idx'),
        ),
        migrations.AddIndex(
            model_name='sicopcarteles',
            index=models.Index(fields=['FECHAH_APERTURA'], name='sicop_carte_FECHAH__be45cc_idx'),
        ),
        migrations.AddIndex(
            model_name='sicopcarteles',
            index=models.Index(fields=['NRO_SICOP'], name='sicop_carte_NRO_SIC_fab929_idx'),
        ),
    ]
