# Generated by Django 6.0.8 on 2026-08-28 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicop', '0003_sicopadjudicacionesfirme_sicop_adjud_nro_sic_091c4b_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorridaPaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrida', models.TextField(blank=True, null=True)),
                ('paso', models.TextField(blank=True, null=True)),
                ('estado', models.TextField(blank=True, null=True)),
                ('detalle', models.TextField(blank=True, null=True)),
                ('filas', models.BigIntegerField(blank=True, null=True)),
                ('duracion_ms', models.BigIntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'corrida_paso',
                'ordering': ['corrida', 'id'],
                'indexes': [models.Index(fields=['corrida'], name='corrida_pas_corrida_f445d6_idx')],
            },
        ),
    ]
