# Generated by Django 6.0.8 on 2026-08-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicop', '0004_corridapaso'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sicopinvitaciones',
            index=models.Index(fields=['CEDULA_PROVEEDOR'], name='sicop_invit_CEDULA__668ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='sicoplineasadjudicadas',
            index=models.Index(fields=['NRO_SICOP'], name='sicop_linea_NRO_SIC_f2e520_idx'),
        ),
        migrations.AddIndex(
            model_name='sicoplineascartel',
            index=models.Index(fields=['NRO_SICOP'], name='sicop_linea_NRO_SIC_d3fd97_idx'),
        ),
        migrations.AddIndex(
            model_name='sicoplineascontratadas',
            index=models.Index(fields=['NRO_SICOP'], name='sicop_linea_NRO_SIC_456746_idx'),
        ),
        migrations.AddIndex(
            model_name='sicoplineasofertadas',
            index=models.Index(fields=['NRO_SICOP'], name='sicop_linea_NRO_SIC_c5f5b2_idx'),
        ),
        migrations.AddIndex(
            model_name='sicoplineasrecibidas',
            index=models.Index(fields=['NRO_SICOP'], name='sicop_linea_NRO_SIC_ad89ea_idx'),
        ),
        migrations.AddIndex(
            model_name='sicopordenespedido',
            index=models.Index(fields=['CEDULAPROVEEDOR'], name='sicop_orden_CEDULAP_4d050f_idx'),
        ),
    ]
