# Generated by Django 6.0.8 on 2026-08-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sicop', '0006_goldmespublicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sicopadjudicaciones',
            name='MES_ZIP',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sicopadjudicacionesfirme',
            name='MES_ZIP',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sicopcarteles',
            name='MES_ZIP',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sicopcontratos',
            name='MES_ZIP',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sicopetapas',
            name='MES_ZIP',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sicopevaluacionofertas',
            name='MES_ZIP',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sicopgarantias',
            name='MES_ZIP',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sicopinhibiciones',
            name='MES_ZIP',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sicopinstituciones',
            name='MES_ZIP',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sicopinvitaciones',
            name='MES_ZIP',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sicoplineasadjudicadas',
            name='MES_ZIP',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sicoplineascartel',
            name='MES_ZIP',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sicoplineascontratadas',
            name='MES_ZIP',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sicoplineasofertadas',
            name='MES_ZIP',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sicoplineasrecibidas',
            name='MES_ZIP',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sicopofertas',
            name='MES_ZIP',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sicopordenespedido',
            name='MES_ZIP',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sicopprocedimientosadm',
            name='MES_ZIP',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sicopproveedores',
            name='MES_ZIP',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sicopreajustes',
            name='MES_ZIP',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sicoprecepciones',
            name='MES_ZIP',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sicoprecursos',
            name='MES_ZIP',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sicopremates',
            name='MES_ZIP',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='sicopsancionesregistro',
            name='MES_ZIP',
            field=models.TextField(blank=True, db_index=True, null=True),
        ),
    ]
