# Modelos que existian en el codigo SIN migracion previa (deriva detectada
# 2026-09-30). En la VPS las tablas ya existian; en instalaciones nuevas no.
# Por eso se registran en el estado con CreateModel pero el DDL usa
# CREATE TABLE/INDEX IF NOT EXISTS: funciona si la tabla falta y no rompe si ya
# esta (VPS). Un CreateModel normal tumbaba `migrate` y con el el arranque de
# django (su comando es `migrate && gunicorn`).
from django.db import migrations, models

_DRIFT_DDL = [
    """CREATE TABLE IF NOT EXISTS ctl_retencion (
        id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        corrida text NOT NULL,
        anio integer NOT NULL,
        dry_run boolean NOT NULL,
        total_filas bigint NULL,
        estado text NULL,
        detalle text NULL,
        creado_en timestamp with time zone NOT NULL
    )""",
    """CREATE TABLE IF NOT EXISTS ctl_trampa (
        id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        conjunto text NOT NULL,
        campo text NOT NULL,
        trampa text NOT NULL,
        cargado_en timestamp with time zone NOT NULL
    )""",
    """CREATE UNIQUE INDEX IF NOT EXISTS ctl_trampa_conjunto_campo_key
        ON ctl_trampa (conjunto, campo)""",
    """CREATE TABLE IF NOT EXISTS dim_entidad (
        id bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        tipo text NOT NULL,
        cedula text NOT NULL,
        nombre text NOT NULL,
        nombre_norm text NOT NULL,
        alias jsonb NOT NULL,
        alias_norm jsonb NOT NULL,
        activo boolean NOT NULL
    )""",
    """CREATE UNIQUE INDEX IF NOT EXISTS dim_entidad_tipo_cedula_key
        ON dim_entidad (tipo, cedula)""",
]


class Migration(migrations.Migration):

    dependencies = [
        ('sicop', '0007_mes_zip_columna'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='CtlRetencion',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('corrida', models.TextField()),
                        ('anio', models.IntegerField()),
                        ('dry_run', models.BooleanField(default=True)),
                        ('total_filas', models.BigIntegerField(blank=True, null=True)),
                        ('estado', models.TextField(blank=True, null=True)),
                        ('detalle', models.TextField(blank=True, null=True)),
                        ('creado_en', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'db_table': 'ctl_retencion',
                    },
                ),
                migrations.CreateModel(
                    name='CtlTrampa',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('conjunto', models.TextField()),
                        ('campo', models.TextField()),
                        ('trampa', models.TextField()),
                        ('cargado_en', models.DateTimeField(auto_now_add=True)),
                    ],
                    options={
                        'db_table': 'ctl_trampa',
                        'constraints': [models.UniqueConstraint(fields=('conjunto', 'campo'), name='ctl_trampa_conjunto_campo_key')],
                    },
                ),
                migrations.CreateModel(
                    name='DimEntidad',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('tipo', models.TextField()),
                        ('cedula', models.TextField()),
                        ('nombre', models.TextField()),
                        ('nombre_norm', models.TextField()),
                        ('alias', models.JSONField(default=list)),
                        ('alias_norm', models.JSONField(default=list)),
                        ('activo', models.BooleanField(default=True)),
                    ],
                    options={
                        'db_table': 'dim_entidad',
                        'constraints': [models.UniqueConstraint(fields=('tipo', 'cedula'), name='dim_entidad_tipo_cedula_key')],
                    },
                ),
            ],
            database_operations=[migrations.RunSQL(sql) for sql in _DRIFT_DDL],
        ),
        migrations.CreateModel(
            name='CtlSello',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corrida', models.TextField(blank=True, null=True)),
                ('artefacto', models.TextField(blank=True, null=True)),
                ('sha256', models.TextField(blank=True, null=True)),
                ('tamano_bytes', models.BigIntegerField(blank=True, null=True)),
                ('rol', models.TextField(blank=True, null=True)),
                ('sellado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ctl_sello',
                'indexes': [models.Index(fields=['corrida'], name='ctl_sello_corrida_2daa78_idx')],
                'constraints': [models.UniqueConstraint(fields=('corrida', 'artefacto'), name='ctl_sello_corrida_artefacto_key')],
            },
        ),
        migrations.CreateModel(
            name='SicopLineasSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ARCHIVO_ORIGEN', models.TextField(blank=True, db_index=True, null=True)),
                ('MES_ZIP', models.TextField(blank=True, db_index=True, null=True)),
                ('MES_PUBLICACION', models.TextField(blank=True, db_index=True, null=True)),
                ('NRO_SICOP', models.TextField(blank=True, null=True)),
                ('NUMERO_LINEA', models.TextField(blank=True, null=True)),
                ('NUMERO_PARTIDA', models.TextField(blank=True, null=True)),
                ('DESC_LINEA', models.TextField(blank=True, null=True)),
                ('CEDULA_INSTITUCION', models.TextField(blank=True, null=True)),
                ('NRO_PROCEDIMIENTO', models.TextField(blank=True, null=True)),
                ('TIPO_PROCEDIMIENTO', models.TextField(blank=True, null=True)),
                ('FECHA_PUBLICACION', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'lineas_sistema',
                'db_table': 'sicop_lineas_sistema',
                'indexes': [models.Index(fields=['NRO_SICOP'], name='sicop_linea_NRO_SIC_ef2aed_idx')],
            },
        ),
    ]
